/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeaderComponent: typeof import('./src/components/AppHeaderComponent.vue')['default']
    BuscarDeudaComponent: typeof import('./src/components/pasos/BuscarDeudaComponent.vue')['default']
    DatosParaFacturaComponent: typeof import('./src/components/pasos/pagar/DatosParaFacturaComponent.vue')['default']
    Default: typeof import('./src/components/default.vue')['default']
    DialogLoadingComponent: typeof import('./src/components/DialogLoadingComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PagarComponent: typeof import('./src/components/pasos/pagar/PagarComponent.vue')['default']
    PagosSeleccionadosComponent: typeof import('./src/components/pasos/pagar/PagosSeleccionadosComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeleccionarPagoComponent: typeof import('./src/components/pasos/SeleccionarPagoComponent.vue')['default']
  }
}
